name: Build and Run C++ IPLocation

on:
  push:
  pull_request:

jobs:
  test-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile IPLocation C++ (no Arduino)
        run: |
          g++ examples/CppUsage/main.cpp src/IPLocation.cpp -o iplocation -std=c++17

      - name: Get public IP
        id: ip
        run: |
          echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Run program with current IP
        run: |
          echo "Using public IP: ${{ steps.ip.outputs.ip }}"
          ./iplocation ${{ steps.ip.outputs.ip }}